# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EbiznesTyl

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3c9d88d6732b4385b2dbe10fe44b7f98 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8f3c032fe7ed41d38151d6fc34261bac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/ppitu/e-biznes:latest #${{ secrets.AzureAppService_ContainerUsername_3c9d88d6732b4385b2dbe10fe44b7f98 }}/ppitu/e-biznes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EbiznesTyl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f7a722db36b46eb8246219804a9ad97 }}
        images: 'index.docker.io/ppitu/e-biznes:latest' # ${{ secrets.AzureAppService_ContainerUsername_3c9d88d6732b4385b2dbe10fe44b7f98 }}/ppitu/e-biznes:${{ github.sha }}'
