# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ppitu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_96509cc124a7412db9aab5b6132c529a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7c37e4b2899e41349997c1ad4bdb0ea5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_96509cc124a7412db9aab5b6132c529a }}/ppitu/ebiznes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ppitu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4ed8b213cb044fd3bd0624c343232afc }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_96509cc124a7412db9aab5b6132c529a }}/ppitu/ebiznes:${{ github.sha }}'
