# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EbiznesTyl

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_68759c1f5a0944fcb302e81cab344d8f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dd4191166d3740b1b840178a48d1a4f8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_68759c1f5a0944fcb302e81cab344d8f }}/e-biznes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EbiznesTyl'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4afaae3c3b8648d5b28d21a9e4ef272f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_68759c1f5a0944fcb302e81cab344d8f }}/e-biznes:${{ github.sha }}'